#Short command to extract the public IP generated by the elastic IP, outputs will be shown when I perform a terraform apply or terraform refresh
#create more of these outputs to extract whatever you want
output "url" {
  value = aws_eip.one.public_ip
}
